# Generated by Django 5.1.2 on 2024-10-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='menu_item_description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
